SELECT DISTINCT
    /*Relation between Nodes in PTMS, e.g. TPM to Glpt, ECLASS, ECLASS S
    Used tables/views: 
    products.wsstd.dv.p2r::DV_PNCMP
    MV_PTMS_NODE_RELATIONS 
    MV_PTMS_NODE_NAME
    MV_PTMS_NODE_RELATIONS_ECLASS_S_ECLASS_GLPT
     */
    PNCMP.PNGUID AS "TPM_PNGUID",
    NODE_NAME.PNAME AS "TPM",
    NODE_NAME.PNTEXT_UP AS "TPMTXT",
    NODE_RELATIONS_ECLASS.GLPT_PNGUID AS "GLPT_PNGUID",
    NODE_RELATIONS_ECLASS.GLPT AS "GLPT",
    NODE_RELATIONS_ECLASS.GLPTTXT AS "GLPTTXT",
    NODE_RELATIONS_ECLASS.ECLASS_PNGUID AS "ECLASS_PNGUID",
    NODE_RELATIONS_ECLASS.ECLASS AS "ECLASS",
    NODE_RELATIONS_ECLASS.ECLASSTXT AS "ECLASSTXT",
    NODE_RELATIONS_ECLASS.ECLASS_S_PNGUID AS "ECLASS_S_PNGUID",
    NODE_RELATIONS_ECLASS.ECLASS_S AS "ECLASS_S",
    NODE_RELATIONS_ECLASS.ECLASS_STXT AS "ECLASS_STXT"
FROM
    (
        RXWSSTD."products.wsstd.dv.p2r::DV_PNCMP" PNCMP
        INNER JOIN (
            SXOKEDSX.MV_PTMS_NODE_RELATIONS NODE_RELATIONS
            INNER JOIN SXOKEDSX.MV_PTMS_NODE_RELATIONS_ECLASS_S_ECLASS_GLPT NODE_RELATIONS_ECLASS ON NODE_RELATIONS.NODEID_PNGUID = NODE_RELATIONS_ECLASS.GLPT_PNGUID
        ) ON PNCMP.TPM_MASTER_GUID = NODE_RELATIONS.NODE_ITEMID_PNGUID
    )
    INNER JOIN SXOKEDSX.MV_PTMS_NODE_NAME NODE_NAME ON PNCMP.PNGUID = NODE_NAME.PNGUID
WHERE
    NODE_RELATIONS.NODE_ITEMPNTYPE = 'Z_TPM'
    AND NODE_RELATIONS.NODEPNTYPE = 'Z_PT_GL'