SELECT DISTINCT
/* Information on all Documents linked to OBject ID (Material or TPM)
* Used Tables/Views:
	SXOKEDSX.MV_DOC_INFO_CURRENT
 	SXOKEDSX.MV_P2R_DRAWING_TYPE
*/
	DOCINFO.OBJKY AS "OBJKY",
	DOCINFO.MATNR,
	DOCINFO.MATNR8,
	DOCINFO.TPM,
	DOCINFO.PNGUID,
	--LRA
	MAX(CASE WHEN DOCINFO.DOKAR = 'LRA' THEN DOCINFO.DOKNR ELSE NULL END) AS "LRA",
		MAX(CASE WHEN DOCINFO.DOKAR = 'LRA' THEN DOCINFO.MAX_DOKVR ELSE NULL END) AS "LRA_VERSION",
		MAX(CASE WHEN DOCINFO.DOKAR = 'LRA' THEN DOCINFO.ADATUM ELSE NULL END) AS "LRA_DATE",
		max(CASE WHEN DOCINFO.DOKAR = 'LRA' THEN DOCINFO.DKTXT_UC ELSE NULL END) AS "LRA_DKTXT_UC",
		max(CASE WHEN DOCINFO.DOKAR = 'LRA' THEN DOCINFO.FILENAME ELSE NULL END) AS "LRA_FILENAME",
	--HRL
	Max(CASE WHEN DOCINFO.DOKAR = 'HRL' THEN DOCINFO.DOKNR ELSE NULL END) AS "HRL",
		MAX(CASE WHEN DOCINFO.DOKAR = 'HRL' THEN DOCINFO.MAX_DOKVR ELSE NULL END) AS "HRL_VERSION",
		MAX(CASE WHEN DOCINFO.DOKAR = 'HRL' THEN DOCINFO.ADATUM ELSE NULL END) AS "HRL_DATE",
		MAX(CASE WHEN DOCINFO.DOKAR = 'HRL' THEN DOCINFO.DKTXT_UC ELSE NULL END) AS "HRL_DKTXT_UC",
	--PMS
	MAX(CASE WHEN DOCINFO.DOKAR = 'PMS' AND DOCINFO.DOKTL='EN' THEN DOCINFO.DOKNR ELSE NULL END) AS "PMS_EN",
		MAX(CASE WHEN DOCINFO.DOKAR = 'PMS' AND DOCINFO.DOKTL='EN' THEN DOCINFO.MAX_DOKVR ELSE NULL END) AS "PMS_VERSION_EN",
		MAX(CASE WHEN DOCINFO.DOKAR = 'PMS' AND DOCINFO.DOKTL='EN' THEN DOCINFO.ADATUM  ELSE NULL END) AS "PMS_DATE_EN",
	MAX(CASE WHEN DOCINFO.DOKAR = 'PMS' AND DOCINFO.DOKTL='DE' THEN DOCINFO.DOKNR ELSE NULL END) AS "PMS_DE",
		MAX(CASE WHEN DOCINFO.DOKAR = 'PMS' AND DOCINFO.DOKTL='DE' THEN DOCINFO.MAX_DOKVR ELSE NULL END) AS "PMS_VERSION_DE",
		MAX(CASE WHEN DOCINFO.DOKAR = 'PMS' AND DOCINFO.DOKTL='DE' THEN DOCINFO.ADATUM  ELSE NULL END) AS "PMS_DATE_DE",
	--ACS
	MAX(CASE WHEN DOCINFO.DOKAR = 'ACS' THEN DOCINFO.DOKNR ELSE NULL END) AS "ACS",
		MAX(CASE WHEN DOCINFO.DOKAR = 'ACS' THEN DOCINFO.MAX_DOKVR ELSE NULL END) AS "ACS_VERSION",
		MAX(CASE WHEN DOCINFO.DOKAR = 'ACS' THEN DOCINFO.ADATUM ELSE NULL END) AS "ACS_DATE",
		MAX(CASE WHEN DOCINFO.DOKAR = 'ACS' THEN DOCINFO.DKTXT_UC ELSE NULL END) AS "ACS_DKTXT_UC",
	--RMS
	MAX(CASE WHEN DOCINFO.DOKAR = 'RMS' THEN DOCINFO.DOKNR ELSE NULL END) AS "RMS",
		MAX(CASE WHEN DOCINFO.DOKAR = 'RMS' THEN DOCINFO.MAX_DOKVR ELSE NULL END) AS "RMS_VERSION",
		MAX(CASE WHEN DOCINFO.DOKAR = 'RMS' THEN DOCINFO.ADATUM  ELSE NULL END) AS "RMS_DATE",
		MAX(CASE WHEN DOCINFO.DOKAR = 'RMS' THEN DOCINFO.DKTXT_UC ELSE NULL END) AS "RMS_DKTXT_UC",
	--Drawings
		--COunt
	MAX(SUB_DRA.ROW_NUM) AS "DRA_COUNT",	
	MAX(SUB_DRA_COMB.DRA_AGG) AS "DRA_COMBINATION_AGG",
	MAX(SUB_DRA_COMB.DRA_AGG_DKTXTUC) AS "DRA_COMBINATION_AGG_DKTXTUC",
	MAX(SUB_DRA_DIE.DRA_AGG) AS "DRA_DIELINE_AGG",
	MAX(SUB_DRA_DIE.DRA_AGG_DKTXTUC) AS "DRA_DIELINE_AGG_DKTXTUC",
	MAX(SUB_DRA_OTHER.DRA_AGG) AS "DRA_OTHER_AGG",
	MAX(SUB_DRA_OTHER.DRA_AGG_DKTXTUC) AS "DRA_OTHER_AGG_DKTXTUC",
	MAX(CASE WHEN SUB_DRA.ROW_NUM = 1 THEN SUB_DRA.DOKNR ELSE NULL END) AS "DRA_1",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 1 THEN SUB_DRA.MAX_DOKVR ELSE NULL END) AS "DRA_VERSION_1",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 1 THEN SUB_DRA.DKTXT_UC ELSE NULL END) AS "DRA_DKTXT_UC_1",
	MAX(CASE WHEN SUB_DRA.ROW_NUM = 2 THEN SUB_DRA.DOKNR ELSE NULL END) AS "DRA_2",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 2 THEN SUB_DRA.MAX_DOKVR ELSE NULL END) AS "DRA_VERSION_2",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 2 THEN SUB_DRA.DKTXT_UC ELSE NULL END) AS "DRA_DKTXT_UC_2",
	MAX(CASE WHEN SUB_DRA.ROW_NUM = 3 THEN SUB_DRA.DOKNR ELSE NULL END) AS "DRA_3",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 3 THEN SUB_DRA.MAX_DOKVR ELSE NULL END) AS "DRA_VERSION_3",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 3 THEN SUB_DRA.DKTXT_UC ELSE NULL END) AS "DRA_DKTXT_UC_3",
	MAX(CASE WHEN SUB_DRA.ROW_NUM = 4 THEN SUB_DRA.DOKNR ELSE NULL END) AS "DRA_4",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 4 THEN SUB_DRA.MAX_DOKVR ELSE NULL END) AS "DRA_VERSION_4",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 4 THEN SUB_DRA.DKTXT_UC ELSE NULL END) AS "DRA_DKTXT_UC_4",
	MAX(CASE WHEN SUB_DRA.ROW_NUM = 5 THEN SUB_DRA.DOKNR ELSE NULL END) AS "DRA_5",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 5 THEN SUB_DRA.MAX_DOKVR ELSE NULL END) AS "DRA_VERSION_5",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 5 THEN SUB_DRA.DKTXT_UC ELSE NULL END) AS "DRA_DKTXT_UC_5",
	MAX(CASE WHEN SUB_DRA.ROW_NUM = 6 THEN SUB_DRA.DOKNR ELSE NULL END) AS "DRA_6",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 6 THEN SUB_DRA.MAX_DOKVR ELSE NULL END) AS "DRA_VERSION_6",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 6 THEN SUB_DRA.DKTXT_UC ELSE NULL END) AS "DRA_DKTXT_UC_6",
	MAX(CASE WHEN SUB_DRA.ROW_NUM = 7 THEN SUB_DRA.DOKNR ELSE NULL END) AS "DRA_7",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 7 THEN SUB_DRA.MAX_DOKVR ELSE NULL END) AS "DRA_VERSION_7",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 7 THEN SUB_DRA.DKTXT_UC ELSE NULL END) AS "DRA_DKTXT_UC_7",
	MAX(CASE WHEN SUB_DRA.ROW_NUM = 8 THEN SUB_DRA.DOKNR ELSE NULL END) AS "DRA_8",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 8 THEN SUB_DRA.MAX_DOKVR ELSE NULL END) AS "DRA_VERSION_8",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 8 THEN SUB_DRA.DKTXT_UC ELSE NULL END) AS "DRA_DKTXT_UC_8",
	MAX(CASE WHEN SUB_DRA.ROW_NUM = 9 THEN SUB_DRA.DOKNR ELSE NULL END) AS "DRA_9",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 9 THEN SUB_DRA.MAX_DOKVR ELSE NULL END) AS "DRA_VERSION_9",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 9 THEN SUB_DRA.DKTXT_UC ELSE NULL END) AS "DRA_DKTXT_UC_9",
	MAX(CASE WHEN SUB_DRA.ROW_NUM = 10 THEN SUB_DRA.DOKNR ELSE NULL END) AS "DRA_10",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 10 THEN SUB_DRA.MAX_DOKVR ELSE NULL END) AS "DRA_VERSION_10",
		MAX(CASE WHEN SUB_DRA.ROW_NUM = 10 THEN SUB_DRA.DKTXT_UC ELSE NULL END) AS "DRA_DKTXT_UC_10",
		--PDR
	MAX(SUB_PDR_AGG.PDR_AGG) AS "PDR_AGG",
	MAX(SUB_PDR_AGG.PDR_AGG_DKTXTUC) AS "PDR_AGG_DKTXTUC",
	MAX(SUB_PDR.ROW_NUM) AS "PDR_COUNT",
	MAX(CASE WHEN SUB_PDR.ROW_NUM = 1 THEN SUB_PDR.DOKNR ELSE NULL END) AS "PDR_1",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 1 THEN SUB_PDR.MAX_DOKVR ELSE NULL END) AS "PDR_VERSION_1",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 1 THEN SUB_PDR.DKTXT_UC ELSE NULL END) AS "PDR_DKTXT_UC_1",
	MAX(CASE WHEN SUB_PDR.ROW_NUM = 2 THEN SUB_PDR.DOKNR ELSE NULL END) AS "PDR_2",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 2 THEN SUB_PDR.MAX_DOKVR ELSE NULL END) AS "PDR_VERSION_2",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 2 THEN SUB_PDR.DKTXT_UC ELSE NULL END) AS "PDR_DKTXT_UC_2",
	MAX(CASE WHEN SUB_PDR.ROW_NUM = 3 THEN SUB_PDR.DOKNR ELSE NULL END) AS "PDR_3",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 3 THEN SUB_PDR.MAX_DOKVR ELSE NULL END) AS "PDR_VERSION_3",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 3 THEN SUB_PDR.DKTXT_UC ELSE NULL END) AS "PDR_DKTXT_UC_3",
	MAX(CASE WHEN SUB_PDR.ROW_NUM = 4 THEN SUB_PDR.DOKNR ELSE NULL END) AS "PDR_4",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 4 THEN SUB_PDR.MAX_DOKVR ELSE NULL END) AS "PDR_VERSION_4",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 4 THEN SUB_PDR.DKTXT_UC ELSE NULL END) AS "PDR_DKTXT_UC_4",
	MAX(CASE WHEN SUB_PDR.ROW_NUM = 5 THEN SUB_PDR.DOKNR ELSE NULL END) AS "PDR_5",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 5 THEN SUB_PDR.MAX_DOKVR ELSE NULL END) AS "PDR_VERSION_5",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 5 THEN SUB_PDR.DKTXT_UC ELSE NULL END) AS "PDR_DKTXT_UC_5",
	MAX(CASE WHEN SUB_PDR.ROW_NUM = 6 THEN SUB_PDR.DOKNR ELSE NULL END) AS "PDR_6",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 6 THEN SUB_PDR.MAX_DOKVR ELSE NULL END) AS "PDR_VERSION_6",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 6 THEN SUB_PDR.DKTXT_UC ELSE NULL END) AS "PDR_DKTXT_UC_6",
	MAX(CASE WHEN SUB_PDR.ROW_NUM = 7 THEN SUB_PDR.DOKNR ELSE NULL END) AS "PDR_7",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 7 THEN SUB_PDR.MAX_DOKVR ELSE NULL END) AS "PDR_VERSION_7",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 7 THEN SUB_PDR.DKTXT_UC ELSE NULL END) AS "PDR_DKTXT_UC_7",
	MAX(CASE WHEN SUB_PDR.ROW_NUM = 8 THEN SUB_PDR.DOKNR ELSE NULL END) AS "PDR_8",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 8 THEN SUB_PDR.MAX_DOKVR ELSE NULL END) AS "PDR_VERSION_8",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 8 THEN SUB_PDR.DKTXT_UC ELSE NULL END) AS "PDR_DKTXT_UC_8",
	MAX(CASE WHEN SUB_PDR.ROW_NUM = 9 THEN SUB_PDR.DOKNR ELSE NULL END) AS "PDR_9",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 9 THEN SUB_PDR.MAX_DOKVR ELSE NULL END) AS "PDR_VERSION_9",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 9 THEN SUB_PDR.DKTXT_UC ELSE NULL END) AS "PDR_DKTXT_UC_9",
	MAX(CASE WHEN SUB_PDR.ROW_NUM = 10 THEN SUB_PDR.DOKNR ELSE NULL END) AS "PDR_10",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 10 THEN SUB_PDR.MAX_DOKVR ELSE NULL END) AS "PDR_VERSION_10",
		MAX(CASE WHEN SUB_PDR.ROW_NUM = 10 THEN SUB_PDR.DKTXT_UC ELSE NULL END) AS "PDR_DKTXT_UC_10"
FROM 
	SXOKEDSX.MV_DOC_INFO_CURRENT DOCINFO
	--Drawings
	LEFT JOIN (SELECT 
		cur.OBJKY AS "OBJKY",
		cur.DOKNR AS "DOKNR",
		cur.MAX_DOKVR AS "MAX_DOKVR",
		cur.DKTXT_UC AS "DKTXT_UC",
		ROW_NUMBER() OVER (
          PARTITION BY
          cur.Objky
          ORDER BY 
           cur.objky, cur.doknr
          ) row_num
		FROM 
		SXOKEDSX.MV_DOC_INFO_CURRENT cur
		WHERE 
		cur.DOKAR ='DRA'
		GROUP BY cur.objky, cur.DOKNR, cur.MAX_DOKVR,cur.DKTXT_UC
		) SUB_DRA ON DOCINFO.OBJKY = SUB_DRA.OBJKY
	--PDR
		LEFT JOIN (SELECT 
		cur.OBJKY AS "OBJKY",
		cur.DOKNR AS "DOKNR",
		cur.MAX_DOKVR AS "MAX_DOKVR",
		cur.DKTXT_UC AS "DKTXT_UC",
		ROW_NUMBER() OVER (
          PARTITION BY
          cur.Objky
          ORDER BY 
           cur.objky, cur.doknr
          ) row_num
		FROM 
		SXOKEDSX.MV_DOC_INFO_CURRENT cur
		WHERE 
		cur.DOKAR ='PDR'
		GROUP BY cur.objky, cur.DOKNR, cur.MAX_DOKVR, cur.DKTXT_UC
		) SUB_PDR ON DOCINFO.OBJKY = SUB_PDR.OBJKY
		--PDR Aggregated
	LEFT JOIN (
		SELECT 
			cur.OBJKY AS "OBJKY",
			string_agg(cur.DOKNR,',') AS "PDR_AGG",
			string_agg(cur.DKTXT_UC,',') AS "PDR_AGG_DKTXTUC"
			FROM
			SXOKEDSX.MV_DOC_INFO_CURRENT cur
			WHERE cur.DOKAR = 'PDR'
			GROUP BY cur.objky	
	) SUB_PDR_AGG
	ON DOCINFO.OBJKY = SUB_PDR_AGG.OBJKY
			--Combination Drawing(s) Aggregated
	LEFT JOIN
			(SELECT 
				cur.OBJKY AS "DRA_OBJKY",
				string_Agg(cur.DOKNR,',') AS "DRA_AGG",
				string_Agg(cur.DKTXT_UC,',') AS "DRA_AGG_DKTXTUC"
				FROM 
				SXOKEDSX.MV_DOC_INFO_CURRENT cur
				LEFT JOIN SXOKEDSX.MV_P2R_DRAWING_TYPE drawtype ON cur.DOC_STRING = drawtype.DOC_STRING 
				WHERE 
				cur.DOKAR ='DRA' 
				AND drawtype.IS_COMBINATION_DRAWING  = 'yes'
				GROUP BY cur.objky) SUB_DRA_COMB
				ON DOCINFO.OBJKY = SUB_DRA_COMB.DRA_OBJKY
		--Dieline Drawing(s) Aggregated
	LEFT JOIN
			(SELECT 
				cur.OBJKY AS "DRA_OBJKY",
				string_Agg(cur.DOKNR,',') AS "DRA_AGG",
				string_Agg(cur.DKTXT_UC,',') AS "DRA_AGG_DKTXTUC"
				FROM 
				SXOKEDSX.MV_DOC_INFO_CURRENT cur
				LEFT JOIN SXOKEDSX.MV_P2R_DRAWING_TYPE drawtype ON cur.DOC_STRING = drawtype.DOC_STRING 
				WHERE 
				cur.DOKAR ='DRA' 
				AND drawtype.IS_Dieline_DRAWING  = 'yes'
				GROUP BY cur.objky) SUB_DRA_DIE
				ON DOCINFO.OBJKY = SUB_DRA_DIE.DRA_OBJKY
		--Other Drawing(s) Aggregated
	LEFT JOIN
			(SELECT 
				cur.OBJKY AS "DRA_OBJKY",
				string_Agg(cur.DOKNR,',') AS "DRA_AGG",
				string_Agg(cur.DKTXT_UC,',') AS "DRA_AGG_DKTXTUC"
				FROM 
				SXOKEDSX.MV_DOC_INFO_CURRENT cur
				LEFT JOIN SXOKEDSX.MV_P2R_DRAWING_TYPE drawtype ON cur.DOC_STRING = drawtype.DOC_STRING 
				WHERE 
				cur.DOKAR ='DRA' 
				AND drawtype.IS_Other_DRAWING  = 'yes'
				GROUP BY cur.objky) SUB_DRA_OTHER
				ON DOCINFO.OBJKY = SUB_DRA_OTHER.DRA_OBJKY
GROUP BY DOCINFO.OBJKY, DOCINFO.MATNR, 	DOCINFO.MATNR8, DOCINFO.TPM, DOCINFO.PNGUID