SELECT DISTINCT
/* Information on PTMS 017 Class and its Content 
 * Used Tables/Views:
 * MV_P2R_Z09_DATEN
 * MV_P2R_CAWNT
 * products.wsstd.dv.p2r::DV_CABNT
 */
	data_017.OBJEK,
	data_017.doc_string,
	data_017.ATINN,
	ATINN_TXT.ATBEZ AS ATINN_TXT,
	data_017.ATZHL,
	data_017.ATWRT,
	data_017.ATFLV,	
	--CASE WHEN to_CHAR(data_017.ATWRT) = to_char('') THEN to_CHAR(data_017.ATFLV)
	CASE
		WHEN data_017.ATWRT = '' THEN data_017.ATFLV
		WHEN  LT_CAWNT.ATWTB = '' THEN LT_CAWNT.ATWTB
		ELSE data_017.ATWRT
	END AS CONTENT, 	
	CASE
		WHEN data_017.ATWRT = '' THEN data_017.ATFLV
		WHEN data_017.ATWRT = LT_CAWNT.ATWTB_TXT THEN LT_CAWNT.ATWTB
		WHEN LT_CAWNT.ATWTB = '' THEN LT_CAWNT.ATWTB
		ELSE data_017.ATWRT
	END AS CONTENT_TXT
FROM
	SXOKEDSX.MV_P2R_017_DATA data_017
LEFT JOIN SXOKEDSX.MV_P2R_CAWNT LT_CAWNT ON data_017.ATINN = LT_CAWNT.ATINN AND data_017.ATWRT = LT_CAWNT.ATWTB_TXT
LEFT JOIN "RXWSSTD"."products.wsstd.dv.p2r::DV_CABNT" ATINN_TXT ON 	data_017.ATINN = ATINN_TXT.ATINN
WHERE ATINN_TXT.SPRAS = 'E' ORDER BY data_017.objek, data_017.ATINN