SELECT DISTINCT
/* Information on max Version of Documents by Material or TPM
 * Used Tables/Views:
 * SXOKEDSX.MV_DOC_MAX_VERSION
   SXOKEDSX.MV_DOC_RELATIONS
   SXOKEDSX.MV_DOC_NAME
   SXOKEDSX.MV_DOC_FILENAME
 */
relation.OBJKY AS "OBJKY",
relation.MATNR AS "MATNR",
relation.MATNR8 AS "MATNR8",
relation.TPM AS "TPM",
relation.PNGUID AS "PNGUID",
relation.DOKAR AS "DOKAR",
relation.DOKNR AS "DOKNR",
relation.DOKVR AS "MAX_DOKVR",
docname.DOKTL AS "DOKTL",
docname.DKTXT_UC  AS "DKTXT_UC",
docname.ADATUM AS "ADATUM",
max_vers.DOC_STRING AS "DOC_STRING",
fname.FILENAME AS "FILENAME"
FROM 
SXOKEDSX.MV_DOC_MAX_VERSION max_vers
LEFT JOIN SXOKEDSX.MV_DOC_RELATIONS relation ON max_vers.DOC_STRING = relation.DOC_STRING
LEFT JOIN SXOKEDSX.MV_DOC_NAME  docname ON max_vers.DOC_STRING = docname.DOC_STRING
LEFT JOIN SXOKEDSX.MV_DOC_FILENAME fname ON MAX_VERS.DOC_STRING = fname.DOC_STRING
