SELECT DISTINCT
    /*Relation between Nodes in PTMS, e.g. ECLASS_S to ECLASS, GLPT
    Used tables/views: 
    MV_PTMS_NODE_RELATIONS 
     */
    NODE1.NODEID_PNGUID AS "ECLASS_S_PNGUID",
    NODE1.NODE AS "ECLASS_S",
    NODE1.NODETXT AS "ECLASS_STXT",
    NODE2.NODEID_PNGUID AS "ECLASS_PNGUID",
    NODE2.NODE AS "ECLASS",
    NODE2.NODETXT AS "ECLASSTXT",
    NODE2.NODE_ITEMID_PNGUID AS "GLPT_PNGUID",
    NODE2.NODE_ITEM AS "GLPT",
    NODE2.NODE_ITEMTXT AS "GLPTTXT"
FROM
    SXOKEDSX.MV_PTMS_NODE_RELATIONS NODE1
    JOIN SXOKEDSX.MV_PTMS_NODE_RELATIONS NODE2 ON NODE1.NODE_ITEMID_PNGUID = NODE2.NODEID_PNGUID
WHERE
    NODE1.NODEPNTYPE = 'Z_ECLASS'
    AND NODE2.NODEPNTYPE = 'Z_ECLASS'
ORDER BY
    NODE1.NODE,
    NODE2.NODE,
    NODE2.NODE_ITEM