SELECT DISTINCT 
/*Relation between Nodes in PTMS, e.g. TA to TPM
  Used tables/views: 
  SXOKEDSX.MV_PTMS_NODE_NAME 
  RXWSSTD."products.wsstd.dv.p2r::DV_PRELID"
*/
PRELID.GUID1 AS "NODEID_PNGUID",
NODE1.PNTYPE AS "NODEPNTYPE", 
NODE1.PNAME AS "NODE", 
NODE1.PNTEXT_UP AS "NODETXT",
PRELID.GUID2 AS "NODE_ITEMID_PNGUID",
NODE2.PNTYPE AS "NODE_ITEMPNTYPE",
NODE2.PNAME AS "NODE_ITEM", 
NODE2.PNTEXT_UP AS "NODE_ITEMTXT",
PRELID.SORT AS "SORT" 
FROM 
	RXWSSTD."products.wsstd.dv.p2r::DV_PRELID" PRELID
	JOIN SXOKEDSX.MV_PTMS_NODE_NAME NODE1 ON PRELID.GUID1 = NODE1.PNGUID 
	JOIN SXOKEDSX.MV_PTMS_NODE_NAME NODE2  ON PRELID.GUID2 = NODE2.PNGUID
WHERE 
	PRELID.OPSYS='P2R'
	AND PRELID.MANDT='508' ORDER BY PRELID.SORT