SELECT DISTINCT
/* Information on Document File Name und Layout Group
 * Used Tables/Views:
 *RXWSSTD."products.wsstd.dv.p2r::DV_DMS_DOC_FILES"
 *SXOKEDSX.MV_DOC_LAYOUT_GROUP LG
**/
	FILES.DOKAR,
    FILES.DOKNR,
    FILES.DOKVR,
    FILES.DOKTL,
    FILES.FILE_IDX,
    FILES.DAPPL,
    FILES.FILENAME,
    REPLACE(FILES.dokar||FILES.doknr||FILES.DOKVR||FILES.DOKTL,' ','') AS "DOC_STRING",
    LG.LGNR AS LAYOUT_GROUP_NR,
    LG.LAYOUT_GROUP_TXT
FROM
    RXWSSTD."products.wsstd.dv.p2r::DV_DMS_DOC_FILES" FILES
    LEFT JOIN SXOKEDSX.MV_DOC_LAYOUT_GROUP LG ON LG."DOC_STRING" = REPLACE(FILES.dokar||FILES.doknr||FILES.DOKVR||FILES.DOKTL,' ','')
    WHERE FILES.DOKAR IN ('ACS','DRA','HRL','LRA','PDR','PMS','RMS')
    AND FILES.OPSYS= 'P2R'
    AND FILES.MANDT= '508'
    AND FILES.OPTYPE <> 'D'