SELECT DISTINCT
    /*Relation between Nodes in PTMS, e.g. TPM to GLPT, ECLASS, ECLASS_S
    Used tables/views: 
    MV_PTMS_NODE_RELATIONS
    MV_PTMS_NODE_RELATIONS_ECLASS_S_ECLASS_GLPT 
     */
    NODERELATIONS.NODE_ITEMID_PNGUID AS "TPM_PNGUID",
    NODERELATIONS.NODE_ITEM AS "TPM",
    NODERELATIONS.NODE_ITEMTXT AS "TPMTXT",
    NODERELATIONS.NODEID_PNGUID AS "GLPT_PNGUID",
    NODERELATIONS.NODE AS "GLPT",
    NODERELATIONS.NODETXT AS "GLPTTXT",
    NODERELATIONS_ECLASS.ECLASS_PNGUID AS "ECLASS_PNGUID",
    NODERELATIONS_ECLASS.ECLASS AS "ECLASS",
    NODERELATIONS_ECLASS.ECLASSTXT AS "ECLASSTXT",
    NODERELATIONS_ECLASS.ECLASS_S_PNGUID AS "ECLASS_S_PNGUID",
    NODERELATIONS_ECLASS.ECLASS_S AS "ECLASS_S",
    NODERELATIONS_ECLASS.ECLASS_STXT AS "ECLASS_STXT"
FROM
    SXOKEDSX.MV_PTMS_NODE_RELATIONS NODERELATIONS
    JOIN SXOKEDSX.MV_PTMS_NODE_RELATIONS_ECLASS_S_ECLASS_GLPT NODERELATIONS_ECLASS ON NODERELATIONS.NODEID_PNGUID = NODERELATIONS_ECLASS.GLPT_PNGUID
WHERE
    NODERELATIONS.NODE_ITEMPNTYPE = 'Z_TPM'
    AND NODERELATIONS.NODEPNTYPE = 'Z_PT_GL'