SELECT DISTINCT
/* Information on PTMS Z09 Class and its Content 
 * Used Tables/Views:
 * MV_P2R_Z09_DATEN
 * MV_P2R_CAWNT
 * products.wsstd.dv.p2r::DV_CABNT
 */
	LT_Z09_Daten.MATNR,
	LT_Z09_Daten.MATNR8,
	LT_Z09_Daten.ATINN,
	ATINN_TXT.ATBEZ AS ATINN_TXT,
	LT_Z09_Daten.ATZHL,
	LT_Z09_Daten.ATWRT,
	LT_Z09_Daten.ATFLV,	
	--CASE WHEN to_CHAR(LT_Z09_Daten.ATWRT) = to_char('') THEN to_CHAR(LT_Z09_Daten.ATFLV)
	CASE
		WHEN LT_Z09_Daten.ATWRT = '' THEN LT_Z09_Daten.ATFLV
		WHEN  LT_CAWNT.ATWTB = '' THEN LT_CAWNT.ATWTB
		ELSE LT_Z09_Daten.ATWRT
	END AS CONTENT, 	
	CASE
		WHEN LT_Z09_Daten.ATWRT = '' THEN LT_Z09_Daten.ATFLV
		WHEN LT_Z09_Daten.ATWRT = LT_CAWNT.ATWTB_TXT THEN LT_CAWNT.ATWTB
		WHEN LT_CAWNT.ATWTB = '' THEN LT_CAWNT.ATWTB
		ELSE LT_Z09_Daten.ATWRT
	END AS CONTENT_TXT
FROM
	SXOKEDSX.MV_P2R_Z09_DATA LT_Z09_Daten
LEFT JOIN SXOKEDSX.MV_P2R_CAWNT LT_CAWNT ON LT_Z09_Daten.ATINN = LT_CAWNT.ATINN AND LT_Z09_Daten.ATWRT = LT_CAWNT.ATWTB_TXT
LEFT JOIN "RXWSSTD"."products.wsstd.dv.p2r::DV_CABNT" ATINN_TXT ON 	LT_Z09_DATEN.ATINN = ATINN_TXT.ATINN
WHERE ATINN_TXT.SPRAS = 'E' ORDER BY MATNR, ATINN